### ISSUE TITLE
@JaEsf needs to be whitelisted

### ISSUE THREAD

**Issue by tayvano** [409H/EtherSecurityLookup#23]
<img width="610" alt="2018-02-19 at 4 58 47 pm" src="https://user-images.githubusercontent.com/7924827/36402908-6b2cda52-1596-11e8-8fb4-64bf07740720.png">

@409H How do I get the Twitter ID of a user? I assume that is what the second field

**Comment by blurpesec** [comment]
@tayvano You use a twitter id lookup site like this: https://tweeterid.com
